import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navigation } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full w-full flex flex-col">
          <div className="h-[64px] w-full">
            <Navigation />
          </div>
          <div className="p-5 min-h-[805px]">{children}</div>
          <div className="h-[64px] w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
